import pytest
from cobrakbase.core.kbasefba.fbamodel_biomass import Biomass


@pytest.fixture
def kbase_biomass1():
    return {
        "biomasscompounds": [
            {
                "coefficient": -41.257,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00067_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00201_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00006_c0",
            },
            {
                "coefficient": -0.186841915485094,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00161_c0",
            },
            {
                "coefficient": -0.0282246669459237,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00062_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd10516_c0",
            },
            {
                "coefficient": 45.354000686262,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00001_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd11493_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00264_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00118_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00063_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00058_c0",
            },
            {
                "coefficient": -0.111039822579957,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00069_c0",
            },
            {
                "coefficient": -0.161028229793075,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00129_c0",
            },
            {
                "coefficient": -0.27042908820211,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00322_c0",
            },
            {
                "coefficient": -0.012738326818085,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00241_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00003_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00099_c0",
            },
            {
                "coefficient": -0.261005044219309,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00053_c0",
            },
            {
                "coefficient": -0.0819482085460939,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00119_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00254_c0",
            },
            {
                "coefficient": -0.0424026391792249,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00038_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00050_c0",
            },
            {
                "coefficient": 0.0123825208335913,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15666_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15560_c0",
            },
            {
                "coefficient": 0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd01997_c0",
            },
            {
                "coefficient": 0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd12370_c0",
            },
            {
                "coefficient": -1,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd17041_c0",
            },
            {
                "coefficient": -0.0141357803930648,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00115_c0",
            },
            {
                "coefficient": -1,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd17043_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00149_c0",
            },
            {
                "coefficient": -0.14832625746843,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00041_c0",
            },
            {
                "coefficient": -0.176188648374102,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00066_c0",
            },
            {
                "coefficient": 1,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd11416_c0",
            },
            {
                "coefficient": -0.323695423757071,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00039_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd10515_c0",
            },
            {
                "coefficient": 0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd03422_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00030_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15766_c0",
            },
            {
                "coefficient": -0.0569540049395353,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00084_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15775_c0",
            },
            {
                "coefficient": -0.0261242266150642,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00052_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15757_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00056_c0",
            },
            {
                "coefficient": -0.0544955586831525,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00065_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00010_c0",
            },
            {
                "coefficient": -0.347460404235438,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00107_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15669_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00087_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00205_c0",
            },
            {
                "coefficient": -0.409331301687739,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00033_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15748_c0",
            },
            {
                "coefficient": -41.2913947104178,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00002_c0",
            },
            {
                "coefficient": -0.0141357803930648,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00357_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00166_c0",
            },
            {
                "coefficient": -0.14832625746843,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00132_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00220_c0",
            },
            {
                "coefficient": -0.012738326818085,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00356_c0",
            },
            {
                "coefficient": -0.0251172136637642,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15540_c0",
            },
            {
                "coefficient": -0.0251172136637642,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15793_c0",
            },
            {
                "coefficient": -0.261005044219309,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00023_c0",
            },
            {
                "coefficient": 41.257,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00008_c0",
            },
            {
                "coefficient": -0.0251172136637642,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15533_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00028_c0",
            },
            {
                "coefficient": -1,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd17042_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00034_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15668_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15352_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00016_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00017_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00048_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd11459_c0",
            },
            {
                "coefficient": -0.193397772168782,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00051_c0",
            },
            {
                "coefficient": -0.11349826883634,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00060_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15667_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15500_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00345_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd15665_c0",
            },
            {
                "coefficient": -0.267560900902997,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00035_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00042_c0",
            },
            {
                "coefficient": 0.184894457580336,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00012_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00037_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00557_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00015_c0",
            },
            {
                "coefficient": -0.00309563020839783,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd02229_c0",
            },
            {
                "coefficient": -0.216753011604418,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00054_c0",
            },
            {
                "coefficient": -0.307715523090583,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00156_c0",
            },
            {
                "coefficient": -0.00719527989638797,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00104_c0",
            },
            {
                "coefficient": 41.2498047201036,
                "edits": {},
                "gapfill_data": {},
                "modelcompound_ref": "~/modelcompounds/id/cpd00009_c0",
            },
        ],
        "cellwall": 0.25,
        "cofactor": 0.1,
        "deleted_compounds": {},
        "dna": 0.026,
        "edits": {},
        "energy": 41.257,
        "id": "bio1",
        "lipid": 0.075,
        "name": "GramPositiveBiomass auto biomass",
        "other": 0,
        "protein": 0.5284,
        "removedcompounds": [],
        "rna": 0.0655,
    }


def test_biomass():
    pass
